### ISSUE TITLE
maak gebruik van (r)em

### ISSUE THREAD

**Issue by SamaraFellaDina** [aliceafanasieva/the-startup-responsive-interactieve-website#2]
```css
.logo {
   width: 96px;
   height: 27px;
}

```
Ik zou van `em` gebruiken maken i.p.v `px`. 

Je kan voor het `.logo` ook een standaard waarde maken. Zelf doe ik altijd iets als:

```css
.logo {
   width: 1.8em;
   height: auto;
}

omdat de height zich dan automatisch aanpast op de breedte, zo gaat de ratio niet.
